#!/usr/bin/python

import sys
from optparse import OptionParser
from codespell import CodeChecker, error

def main():
    parser = OptionParser(usage="%prog [options] filename ...")
    parser.add_option("-u", "--unique", action='store_true',
                      help="report each misspelling only once")
    parser.add_option("-x", "--exclude", action='append', default=[],
                      metavar="STR",
                      help="exclude STR from spell-checking -- strip it from "
                           "input text before splitting into words")
    (options, args) = parser.parse_args()
    if not args:
        parser.error("not enough arguments")

    any_errors = False
    for filename in args:
        try:
            print "checking file %s" % filename
            checker = CodeChecker(filename)
            checker.set_unique(options.unique)
            for s in options.exclude:
                checker.exclude_string(s)
            if checker.check_file():
                any_errors = True
        except IOError, err:
            error("%s: %s" % (filename, err.strerror))
            any_errors = True

    sys.exit(any_errors and 1 or 0)

main()
